services:
  psql:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin

  flask-app:
    build: .
    env_file:
      - .env
    ports:
      - "44444:5000"
    depends_on:
      - psql
    command: >
      sh -c "sleep 5
            rm database/migrations/done/*.sql
            alembic upgrade head
            exec gunicorn --bind 0.0.0.0:5000 app.wsgi:app"

